name: API- Execution

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
        default: "qa1"
      TAGS:
        description: 'Test Scenario tags'
        type: string
        required: true
        default: "@tag1"

  #schedule:
  #  - cron: '30 20 * * 1-5' # Runs at 8:30 PM UTC, Monday to Friday

jobs:
  CustomExecution:
    with:
      javaVersion: 17
      mavenVersion: "3.8.8"
      args: 'mvn clean test -DnewCookies=true -Denv="${{ inputs.ENVIRONMENT }}" -Dcucumber.filter.tags="${{ inputs.TAGS }}"'
      reports_folder: 'target/cucumber-html-reports'